CSS: style.css


## Installation

<pre><div class="sample_code">./configure --prefix=<span class="parameter">PREFIX</span></div></pre>

Where 

<pre><div class="sample_code"><span class="parameter">PREFIX</span></div></pre>

is the name of the root folder where you want apache to live.

     make
     make install

<pre><div class="sample_code"><span class="parameter">PREFIX</span>/bin/apachectl start</div></pre>

If you want SSL.  You may have to install openssl.

Download, and run follow install commands:

<pre><div class="sample_code">./configure --prefix=<span class="parameter">PREFIX</span></div></pre>

     make
     make install


change your configuration line to look like:

<pre><div class="sample_code">./configure --prefix=<span class="parameter">PREFIX</span> <span class="highlight">--enable-ssl</span> <span class="highlight">--with-ssl=</span><span class="parameter">SSL_INSTALL_DIR</span></div></pre>

## Named Virtual Hosts

    # Listen for virtual host requests on all IP addresses
    NameVirtualHost *:80
     
    <VirtualHost *:80>
      ServerName 127.0.0.1
      DocumentRoot /var/www
    </VirtualHost>
     
    <VirtualHost *:80>
      ServerName docs
      DocumentRoot /home/oracle/bin/website   
    </VirtualHost>

## Include

Instead of putting all your configurations into the `httpd.conf` or
`apache.conf` file, you can reference an external file with an
`include` statement.

Providing paths relative to your `ServerRoot` directory:

    Include conf/ssl.conf
    Include conf/vhosts/*.conf


