* wifi-menu -o
* fdisk /dev/sda

make a dos boot partition 'o' i think

1: +60G (use 'a' to make bootable)
2: +170G
3: +8 Swap

set type with ~t~.  83 = linux, 82 = swap.  1,2 are linux, 3 is swap.

* mkfs.ext4 /dev/sda1 & /dev/sda2
* mkswap /dev/sda3; swapon /dev/sda3
* mount /dev/sda1 /mnt
* pacstrap /mnt base
* arch-chroot /mnt
* packages
 + add archlinuxfr repo to /etc/pacman.conf

[archlinuxfr]

Server = http://repo.archlinux.fr/$arch

pacman -Syy

#+BEGIN_SRC 
pacman -S iw wpa_supplicant dialog grub wpa_actiond xorg (maybe
something slimmer like just xserver) awesome emacs jdk8_openjdk clojure
 xorg-xinit xterm xf86-video-intel chromium firefox zsh sudo
openssh rxvt-unicode ttf-dejavu alsa-utils conky base-devel git unzip
autocutsel nodejs npm net-tools pkgfile vlc cups cups-pdf ifplugd slim maven
the_silver_searcher
#+END_SRC


yaourt need signatures...
+ yaourt

#+BEGIN_SRC 
datomic
#+END_SRC

* grub
 + grub-mkconfig -o /boot/grub/grub.cfg
 + grub-install --target=i386-pc /dev/sda 
 + exit; umount /mnt; reboot

remove USB boot media

 + systemctl enable netctl-auto@wlp1s0.service

 + reboot
wifi-menu -o
+ reboot

* add user
useradd -m -G wheel -s /bin/zsh fenton
 + visudo, uncomment wheel no passwd 

+ edit /home/fenton/xinitrc
   
   exec awesome

login as fenton and press 0 for a default .zshrc file

edit /etc/slim.conf so auto login the fenton user

* slim login (display) manager
+ systemctl enable slim

* adjust grub timeout in:
/etc/default/grub

then regenerate grub config with:

 # grub-mkconfig -o /boot/grub/grub.cfg

* copy ssh
mount usb install media on old computer
cp -a .ssh usb

on new computer
cp -a usb/.ssh .
chmod -R 644 .ssh/*
cd .ssh
chmod 600 authorized_keys id_rsa


git clone git@github.com:ftravers/arch-home.git
cp -a arch-home/* .

reboot



* timezone

* copy edit awesome config

* copy/edit rc.lua awesome config file.
** set terminal to terminator
**  comment out floating in layouts

* locale
sudo vi /etc/locale.gen
uncomment: 

#+BEGIN_SRC 
en_US ISO-8859-1
en_US.UTF-8 UTF-8
#+END_SRC

#+BEGIN_SRC 
╭─fenton@archlinux ~  ‹master*› 
╰─➤  cat /etc/locale.conf
LANG=en_US.UTF-8
#+END_SRC

: # sudo locale-gen

* lumo
download, unzip, drop in /bin

* brother printer

** yaourt
Below might be all you have to do

yaourt brother-hll2340dw

Ensure cups is installed.

Go to admin and add printer:

http://localhost:631

** otherwise
The below may or may not help at all.
: sudo pacman -S rpmextract

download lpr and cups hll2320d rpm wrapped drivers from brothers
website

#+BEGIN_SRC 
╭─fenton@archlinux ~/Downloads  ‹master*› 
╰─➤  cd /
╭─fenton@archlinux /  
╰─➤  sudo rpmextract.sh hll2320dcupswrapper-3.2.0-1.i386.rpm 
╭─fenton@archlinux /  
╰─➤  sudo rpmextract.sh hll2320dlpr-3.2.0-1.i386.rpm 
#+END_SRC

#+BEGIN_SRC 
╭─fenton@archlinux ~/docs-DIR/data/brother-printer-drivers  ‹master*› 
╰─➤  pwd
/home/fenton/docs-DIR/data/brother-printer-drivers
╭─fenton@archlinux ~/docs-DIR/data/brother-printer-drivers  ‹master*› 
╰─➤  ls
hll2320dcupswrapper-3.2.0-1.i386.rpm  hll2320dlpr-3.2.0-1.i386.rpm
#+END_SRC

: sudo systemctl enable org.cups.cupsd.service

* gnupg lein

in order to release libraries into clojars need to have dirs:

~/.gnupg and ~/.lein 
* more packages
