* wifi-menu -o
* fdisk /dev/sda

make a dos boot partition 'o' i think

1: +60G (use 'a' to make bootable)
2: +170G
3: +8 Swap

set type with ~t~.  83 = linux, 82 = swap.  1,2 are linux, 3 is swap.

* mkfs.ext4 /dev/sda1 & /dev/sda2
* mkswap /dev/sda3; swapon /dev/sda3
* mount /dev/sda1 /mnt
* pacstrap /mnt base linux linux-firmware
* fstab

: genfstab -U /mnt >> /mnt/etc/fstab
* arch-chroot /mnt
* packages
 + add archlinuxfr repo to /etc/pacman.conf

[archlinuxfr]

Server = http://repo.archlinux.fr/$arch

pacman -Syy

#+BEGIN_SRC 
pacman -S iw wpa_supplicant dialog grub wpa_actiond xorg (maybe
something slimmer like just xserver) awesome emacs jdk8_openjdk clojure
 xorg-xinit xterm xf86-video-intel chromium firefox zsh sudo
openssh rxvt-unicode ttf-dejavu alsa-utils conky base-devel git unzip
autocutsel nodejs npm net-tools pkgfile vlc cups cups-pdf ifplugd slim maven
the_silver_searcher
#+END_SRC


yaourt need signatures...
+ yaourt

#+BEGIN_SRC 
datomic
#+END_SRC

* grub

 + grub-install --target=i386-pc /dev/sda 
 + grub-mkconfig -o /boot/grub/grub.cfg
 + exit; umount /mnt; reboot

remove USB boot media

 + systemctl enable netctl-auto@wlp1s0.service

 + reboot
wifi-menu -o
+ reboot

* add user
useradd -m -G wheel -s /bin/zsh fenton
 + visudo, uncomment wheel no passwd 

+ edit /home/fenton/xinitrc
   
   exec awesome

login as fenton and press 0 for a default .zshrc file

edit /etc/slim.conf so auto login the fenton user

* slim login (display) manager
+ systemctl enable slim

* adjust grub timeout in:
/etc/default/grub

then regenerate grub config with:

 # grub-mkconfig -o /boot/grub/grub.cfg

* copy ssh

** on old machine

#+BEGIN_SRC 
╭─fenton@archlinux ~  ‹master*› 
╰─➤  lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 167.7G  0 disk 
├─sda1   8:1    0   150G  0 part /
└─sda2   8:2    0  17.7G  0 part 
sdc      8:32   1  14.9G  0 disk 
└─sdc1   8:33   1  14.9G  0 part 
╭─fenton@archlinux ~  ‹master*› 
╰─➤  sudo mount /dev/sdc1 usb
╭─fenton@archlinux ~  ‹master*› 
╰─➤  cp -a .ssh usb
╭─fenton@archlinux ~  ‹master*› 
╰─➤  cd usb             
╭─fenton@archlinux ~/usb  
╰─➤  git clone ~                                            128 ↵
Cloning into 'fenton'...
done.
╭─fenton@archlinux ~/usb  
╰─➤  cd ..
╭─fenton@archlinux ~  ‹master*› 
╰─➤  sudo umount usb
#+END_SRC
mount usb install media on old computer
cp -a .ssh usb

** on new computer
: sudo mount /dev/sd?1 usb

where ? above is whatever you get back from ~lsblk~ command.

Install oh-my-zsh

#+BEGIN_SRC 
cp -a usb/.ssh .
chmod -R 644 .ssh/*
cd .ssh
chmod 600 authorized_keys id_rsa
git clone git@github.com:ftravers/arch-home.git
cp -a arch-home/* .
cd ~/usb
cp -a fenton/* ~
mv .zshrc .zshrc-bak
ln -s .zshrc-lenovo .zshrc
#+END_SRC

* get new home dir

Once computer is connected do:

#+BEGIN_SRC 
git config --global user.email "fenton.travers@gmail.com"
git config --global user.name "Fenton Travers"
git clone git@github.com:ftravers/home-dir.git
cd home-dir
cp * .* ..
#+END_SRC

Fire up emacs and see that it downloads and installs all the packages
it needs.

* Xresources

  Pick which .Xresources to use.

: ln -s .Xresources-* .Xresources

sudo pacman -S xcape autocutsel conky rxvt-unicode ntp pkgfile

Link one of the .zshrc-* files

: ln -s .zshrc-dell .zshrc

* copy/edit rc.lua awesome config file.
** set terminal to terminator
** comment out floating in layouts
* timezone
: sudo timedatectl set-timezone America/Vancouver
* locale

sudo vi /etc/locale.gen
uncomment: 

#+BEGIN_SRC 
en_US ISO-8859-1
en_US.UTF-8 UTF-8
#+END_SRC

AS ROOT DO:

#+BEGIN_SRC 
╭─fenton@archlinux ~  ‹master*› 
╰─➤  cat > /etc/locale.conf
LANG=en_US.UTF-8
#+END_SRC

: # sudo locale-gen
# systemctl enable ntpd.service

* --------------------------
* powerline fonts
to have a nice terminal prompt follow:

https://powerline.readthedocs.io/en/latest/installation/linux.html#fonts-installation

* lumo
download, unzip, drop in /bin

* brother printer

** yaourt
Below might be all you have to do

: yaourt brother-hll2340dw

Ensure cups is installed.

: sudo systemctl enable org.cups.cupsd.service

Go to admin and add printer:

http://localhost:631

The above should be sufficient...i got it to work i think without
downloading the rpm's below..., but i may have installed the rpm's
months ago...dunno.

** otherwise

The below may or may not help at all.

: sudo pacman -S rpmextract

download lpr and cups hll2320d rpm wrapped drivers from brothers
website

#+BEGIN_SRC 
╭─fenton@archlinux ~/Downloads  ‹master*› 
╰─➤  cd /
╭─fenton@archlinux /  
╰─➤  sudo rpmextract.sh hll2320dcupswrapper-3.2.0-1.i386.rpm 
╭─fenton@archlinux /  
╰─➤  sudo rpmextract.sh hll2320dlpr-3.2.0-1.i386.rpm 
#+END_SRC

#+BEGIN_SRC 
╭─fenton@archlinux ~/docs-DIR/data/brother-printer-drivers  ‹master*› 
╰─➤  pwd
/home/fenton/docs-DIR/data/brother-printer-drivers
╭─fenton@archlinux ~/docs-DIR/data/brother-printer-drivers  ‹master*› 
╰─➤  ls
hll2320dcupswrapper-3.2.0-1.i386.rpm  hll2320dlpr-3.2.0-1.i386.rpm
#+END_SRC

: sudo systemctl enable org.cups.cupsd.service

* gnupg lein

in order to release libraries into clojars need to have dirs:

~/.gnupg and ~/.lein 
* more packages
* Awesome/conky: show battery, disk full, etc...
  
Check you have the right link in 

: /home/fenton/.config/awesome/rc.lua

Ensure the following line is actually pointing to something:

: awful.util.spawn_with_shell("conky -c ~/.conky/left")

* sound

: /home/fenton/.config/awesome/rc.lua

#+BEGIN_SRC lua
     awful.key({  }, "#122",
--     function (c) awful.util.spawn_with_shell("amixer -D pulse sset Master 10%-") end,
       function (c) awful.util.spawn_with_shell("pactl set-sink-volume -10%") end,
#+END_SRC
