# Background

We have a spreadsheet that we want to make available over the web to
an external application.  Currently the spreadsheet is in a jar
project.

We will create a WAR project that includes the jar, then we'll create
an EAR project that includes the WAR file.

## Create the war project

    cd ~/projects

    mvn archetype:generate -B -DarchetypeArtifactId=maven-archetype-webapp -DgroupId=com.oracle.git.ngsp -DartifactId=categorizationSpreadsheetWar

    cd categorizationSpreadsheetWar/

    mvn eclipse:eclipse

add the dependency to the categorizationSpreadsheet jar into the
pom.xml file

    <dependencies>
      <dependency>
        <groupId>com.oracle.git.ngsp.catSpread</groupId>
        <artifactId>categorizationSpreadsheet</artifactId>
        <version>0.0.8</version>
      </dependency>
    </dependencies>

## Create Java Logic

Now we'll create code that gets the spreadsheet off the classpath and
returns it from a servlet path request.
