# CRM on Demand 

## Count Contacts

You can get a count of the number of contacts you have in the system
by doing the following:

Reports (Tab) > Design Analysis > Employee Contacts > Employee
Contacts Metrics > # of Employee Contacts > Next
