# CRM on Demand 

## Count Contacts

You can get a count of the number of contacts you have in the system
by doing the following:

Reports (Tab) > Design Analysis > Employee Contacts > Employee
Contacts Metrics > # of Employee Contacts > Next

## Joining

On an SR

The following:

JoinFieldValue('<Contact>', [<ContactId>],'<AlternateCity>')

Joins to the '<Contact>' object using the [<ContactId>] foreign key, pulling back the '<AlternateCity>' value.

JoinFieldValue('<ServiceRequest>',[<ServiceRequestId>],'<OwnerId>')

JoinFieldValue('<User>',JoinFieldValue('<ServiceRequest>',[<ServiceRequestId>],'<OwnerId>'),'<EMailAddr>')

JoinFieldValue('<User>', [<OwnerId>], '<EMailAddr>')

JoinFieldValue('<Contact>', [<ContactId>],'<AlternateCountry>')

JoinFieldValue('<Contact>', [<ContactId>],'<AlternateCountry>')

[<OwnerId>]
[<OwnerId>]

JoinFieldValue('<User>', [<OwnerId>], '<EMailAddr>')

Create a new field on the SR Object called: 'Owner Email', make long text.


## Help

https://secure-ausomxfba.crmondemand.com/docs/1.12.0.1220.0.05/enu/help/index.htm?toc.htm?siebelqlsampleexpressionshelp.html

