## Download

Download from: [eDelivery](http://edelivery.oracle.com/)

    Select a Product Pack: Oracle Database
    Platform: Linux x86
    Oracle® Database 11g Release 2 (11.2.0.1.0) Media Pack for Linux x86

## JeOS Template Params

Template setup with the following parameters:

    OS: OEL5U3_32bit
    System: 12288 MB
    Memory: 1024 MB
    Swap: 1536 MB

    [root@db11g u01]# /usr/sbin/groupadd oinstall; /usr/sbin/groupadd dba; /usr/sbin/useradd -g oinstall -G dba oracle; mkdir -p /u01/app/; chown -R oracle:oinstall /u01/app/;chmod -R 775 /u01/app/;passwd oracle

    [root@db11g ~]# cat >> /etc/security/limits.conf  
    oracle soft nproc 2047  
    oracle hard nproc 16384  
    oracle soft nofile 1024  
    oracle hard nofile 65536
     
    [root@db11g ~]# cat >> /etc/pam.d/login  
    session required /lib/security/pam_limits.so  
    session required pam_limits.so
     
    [root@db11g ~]# cat >> /etc/profile  
    if [ $USER = “oracle” ]; then   
    if [ $SHELL = “/bin/ksh” ]; then   
    ulimit -p 16384   
    ulimit -n 65536   
    else   
    ulimit -u 16384 -n 65536   
    fi   
    fi
     
    [root@db11g ~]# cat >> /etc/sysctl.conf  
    kernel.shmall = 2097152   
    kernel.shmmax = 2147483648   
    kernel.shmmni = 4096   
    kernel.sem = 250 32000 100 128   
    fs.file-max = 6815744   
    fs.aio-max-nr = 1048576  
    net.ipv4.ip_local_port_range = 9000 65500   
    net.core.rmem_default = 4194304   
    net.core.rmem_max = 4194304   
    net.core.wmem_default = 262144   
    net.core.wmem_max = 1048576

re-read file to change the current values of the kernel
parameters  

    [root@db11g etc]# /sbin/sysctl -p

Install required packages:  

    [root@db11g ~]# yum install -y libaio-0.3.106 libaio-devel-0.3.106 unixODBC-2.2.11 unixODBC-devel-2.2.11 compat-libstdc++-33-3.2.3-61 make gcc libstdc++-devel elfutils-libelf-devel sysstat binutils glibc-devel gcc-c++ ksh

To install x-windows:   

    [root@db11g ~]# yum groupinstall -y 'X Window System'
     
    [root@db11g ~]# su - oracle  
    [oracle@db11g ~]$ cat >> ~/.bash_profile   
    ORACLE_BASE=/u01/app/oracle  
    ORACLE_SID=orcl  
    ORACLE_HOME=/u01/app/oracle/product/11.1.0/db_1  
    ORACLE_HOSTNAME=db112  
    PATH=$PATH:$ORACLE_HOME/bin  
    export ORACLE_BASE ORACLE_SID ORACLE_HOME ORACLE_HOSTNAME PATH
     
    [oracle@db11g ~]$ unset ORACLE_HOME; unset TNS_ADMIN; exit
 
Re-login so xWindows will work  

    travers-fentons-imac:etc traversfenton$ ssh -X -l asd oracle@db112  
    [oracle@db11gr1 ~]# /u02/db112/runInstaller

You may have to wait > 1 minute for the installer to start so be patient.

choose UTF8 AND ‘Desktop’ install

* Auto Startup and Shutdown of Database and Listener

Login as root and modify `/etc/oratab` file and change last character
to Y for apropriate database.

    [oracle@db112 log]$ vi /etc/oratab

    ORCL:/opt/oracle/111:Y

As root user create new file `/etc/init.d/dbora` (init script for
startup and shutdown the database) with following content:

    [oracle@db112 log]$ su -  
    Password:   
    [root@db112 ~]# cat > /etc/init.d/oracle  

    #!/bin/bash  
    # oracle Init file for starting and stopping
    # Oracle Database. Script is valid for 10g and 11g versions.
     
    # chkconfig: 35 80 30
    # description: Oracle Database startup script
     
    # Source function library.
    . /etc/rc.d/init.d/functions
     
    ORACLE_OWNER="oracle"  
    ORACLE_HOME="/u01/app/oracle/product/11.1.0/db_1/"
     
    case “$1” in  
      start)  
        echo -n $"Starting Oracle DB:"  
        su - $ORACLE_OWNER -c "$ORACLE_HOME/bin/dbstart $ORACLE_HOME"  
        echo "OK"  
        ;;  
      stop)  
        echo -n $"Stopping Oracle DB:"  
        su - $ORACLE_OWNER -c "$ORACLE_HOME/bin/dbshut $ORACLE_HOME"  
        echo "OK"  
        ;;  
      *)  
        echo $"Usage: $0 {start|stop}"  
    esac
     
    [root@db112 ~]# cat > /etc/init.d/oraemctl
     
    #!/bin/bash  
    # oraemctl Starting and stopping Oracle Enterprise Manager Database Control.
    # Script is valid for 10g and 11g versions.
     
    #  chkconfig: 35 80 30
    #  description: Enterprise Manager DB Control startup script
     
    # Source function library.
    . /etc/rc.d/init.d/functions
     
    ORACLE_OWNER="oracle"  
    ORACLE_HOME="/u01/app/oracle/product/11.1.0/db_1/"
     
    case “$1” in  
      start)  
        echo -n $"Starting Oracle EM DB Console:"  
        su - $ORACLE_OWNER -c "$ORACLE_HOME/bin/emctl start dbconsole"  
        echo "OK"  
        ;;  
      stop)  
        echo -n $"Stopping Oracle EM DB Console:"  
        su - $ORACLE_OWNER -c "$ORACLE_HOME/bin/emctl stop dbconsole"  
        echo "OK"  
        ;;  
      *)  
        echo $"Usage: $0 {start|stop}"  
    esac
     
    [root@db112 ~]# chmod 750 /etc/init.d/oracle; chkconfig --add oracle --level 0356; chmod 750 /etc/init.d/oraemctl; chkconfig --add oraemctl --level 0356

The above seems to work for the DB and Listener (most important)
but doesn’t seem to do the trick for the EM Console...

https://dble:1158/em



