CSS: style.css

# Adding a new Repository

## For the impatient...

### Configure security/permissions

Edit config file: 

    gitosis-admin/gitosis.conf

Push up your change

    $ git commit -am"."; git push

### Prep the Project


In the folder you want setup as a git repo

<code><pre>
git init
git remote add origin <span class="sample">git@linux1.hk.oracle.com:testProject.git</span></pre></code>

You must add at least one file...git doesn't do empty directories! :)

    git add .; git commit -m"Initial Commit"
    git push origin master:refs/heads/master

# Go back in time

First find the hash of the commit you want to go to with:

    git log --oneline

Then just do:

    git checkout <hash>

# Finding when a problem was introduced

Sometimes a problem gets introduced into the code and you want to find
out when it got introduced.  You can use the `git bisect` command to
find the offending commit.

    git bisect start
    git bisect good 61d20a3
    git bisect bad master
    
assuming the last known good commit was `61d20a3`.  You will then be
put on a commit halfway between `master` and `61d20a3`.  Then run
whatever it is that you'll do to find the problem, a grep, a compile,
etc...  

If the problem still persists, type:

    git bisect bad

So git will give you a commit 1/2 way between `61d20a3` and the
current commit.  Otherwise `git bisect good` will move you to a commit
in the opposite direction.

## In more detail...

### Edit config file

Edit config file: `gitosis-admin/gitosis.conf`

The following is the template for understanding the format of this
file:

    [group groupName]
    writable = repoName
    members = user1 user2

The fields above that need to be filled in with your specific
information are:

-   `groupName` : This is the name of your project group
-   `repoName` : This is the name of the folder that holds your
    repository/project
-   `user1`, `user2` : This is the name of the user who will belong
    to this group. This must correspond to the filename located in
    `gitosis-admin/keydir/user1.pub`. Note don’t include the `.pub`
    extension.

Example:

    $ cat ~/projects/gitosis-admin/gitosis.conf
    [gitosis]
    [group gitosis-admin]
    writable = gitosis-admin
    members = ftravers@ftravers-laptop
    [group testgroup1]
    members = ftravers@ftravers-laptop @anothergroup
    writable = testrepo1 testrepo2 
    readonly = testrepo3
    ## You can use groups just to avoid listing users multiple times. Note
    ## no writable= or readonly= lines.
    [group anothergroup]
    members = alice bill

where

-   `writable` : defines who has commit privileges
-   `readonly` : defines who has read only privileges
-   `testgroup1` : is the name of the group
-   `testrepo1` : is the name of the new repository
-   `members` : is a space delimeted list of users included in this
    group

The `members` list should be the filenames from
`~/projects/gitosis-admin/keydir` folder without the `.pub`
extension.

### Create a new project and push to server

Now create the project...

    $ cd ~/projects; 

You can create a new empty directory, or copy an existing
directory/files into this folder

-   Without Maven

    $ rm -rf testrepo1; mkdir testrepo1

-   - OR – with Maven

    $ mvn archetype:create -DgroupId=com.mycompany.app -DartifactId=testrepo1

-   Add it to git server

    $ cd testrepo1; git init
    $ git remote add spicevan ft_git3@spicevan.com:testrepo1.git
    $ git remote add origin git@linux1.hk.oracle.com:testrepo1.git

Do some work, git add and commit files like: `test.txt`

If you copy some files into here that you want to then manage,
after the copy do the following:

    $ cd testrepo1
    $ git add .
    $ git commit -m"Initial Commit"
    $ git push origin master:refs/heads/master

# References

-   [Git Reference](http://git.or.cz/course/svn.html)

# Install gitosis on Dreamhost

Reference:
[Dreamhost Gitosis Setup](http://wiki.dreamhost.com/Gitosis)

    $ ssh-keygen -t rsa
    $ ssh-copy-id ft_git3@spicevan.com
    $ rsync -avP --stats .ssh/id_rsa.pub ft_git3@spicevan.com:~

Check your version of python with: `python --version`

-   for JeOS systems see:
    -   [Installing GIT](/applications.html#git)
    -   [Installing Python 2.6](/applications.html#python26)


for 2.5\*

    [remote]$ mkdir -p $HOME/lib/python2.5/site-packages
    [remote]$ export PYTHONPATH=$HOME/lib/python2.5/site-packages
    [remote]$ mkdir ~/src; cd ~/src; wget http://pypi.python.org/packages/2.5/s/setuptools/setuptools-0.6c11-py2.5.egg
    [remote]$ sh setuptools-0.6c11-py2.5.egg --prefix=$HOME

if you need a proxy for wget use something like:

    export http_proxy=http://your.proxy.server:port && wget -c http://whatever

for 2.6\*

    [remote]$ mkdir -p $HOME/lib/python2.6/site-packages
    [remote]$ export PYTHONPATH=$HOME/lib/python2.6/site-packages
    [remote]$ mkdir ~/src; cd ~/src; wget http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c11-py2.6.egg
    [remote]$ sh setuptools-0.6c11-py2.6.egg --prefix=$HOME

The rest is the same for either version.

    [remote]$ git clone git://eagain.net/gitosis.git

If the `git clone git://eagain.net/gitosis.git` line doesn’t work
for you  
like it didn’t for me once, you can download the tar.gz off the web
and   
untar it in your root folder so `cd; ls` shows the `gitosis`
directory.

Maybe get it here:
[http://felixembeddedonandroid.googlecode.com/files/gitosis.tar.gz](http://felixembeddedonandroid.googlecode.com/files/gitosis.tar.gz)

    [remote]$ cd; tar xvfz gitosis-somelongHashCode.tar.gz

The rest should go without a hitch

    [remote]$ cd gitosis/
    [remote]$ export PATH=$HOME/bin:$PATH
    [remote]$ python setup.py install --prefix=$HOME; cd
    [remote]$ echo "export PYTHONPATH=$HOME/lib/python2.5/site-packages/" >> .bashrc
    [remote]$ echo "export PYTHONPATH=$HOME/lib/python2.5/site-packages/" >> .bash_profile
    [remote]$ echo "export PATH=$HOME/bin:$PATH" >> .bashrc
    [remote]$ echo "export PATH=$HOME/bin:$PATH" >> .bash_profile
    [remote]$ . ~/.bash_profile
    [remote]$ gitosis-init < id_rsa.pub; rm -f id_rsa.pub
    [remote]$ chmod 750 $HOME/repositories/gitosis-admin.git/hooks/post-update
    $ mkdir ~/projects; cd ~/projects
    $ git clone ft_git3@spicevan.com:gitosis-admin.git


# When others want to use repository

## Get users public key

Whoever wants to work on the repo must create a public/private key
pair and send you the public key.

[testuser@local]$ ssh-keygen -t rsa  
[testuser@local]$ cp .ssh/id\_rsa.pub \~

Send the administrator of the repository your `~/.ssh/id_rsa.pub`
file.

As the administrator add the file to the `keydir` folder:

    $ cp /home/testuser/id_rsa.pub ~/projects/gitosis-admin/keydir/testuser.pub
    $ cd ~/projects/gitosis-admin/keydir
    $ git add .
    $ cd ..

Now we have their public key we can add them to projects, edit the
`~/projects/gitosis-admin/gitosis.conf` file.

    $ cat ~/projects/gitosis-admin/gitosis.conf
    [gitosis]
    [group gitosis-admin]
    writable = gitosis-admin
    members = ftravers@ftravers-laptop
    [group testgroup1]
    writable = testrepo1
    members = ftravers@ftravers-laptop testuser
    $

Finally push up your changes to the conf file and the added public
key to the server:

    $ git commit -a -m"My Message."
    $ git push

## Clone Repository

Now the other user `testuser` can checkout this repository

    [testuser@local]$ mkdir ~/projects; cd ~/projects
    [testuser@local]$ git clone ft_git3@spicevan.com:testrepo1.git; cd ~/projects/testrepo1
    # make some changes to the file @test.txt@ in the repo and commit and push them back to the server.
    [testuser@local]$ git commit -a -m"My comment.";
    [testuser@local]$ git push

## Pull Updates from Remote Repository

    git pull origin master

# Test merging

In the above section a second user `testuser` modified a file:
`test.txt` that the user `ftravers` also has. So as `ftravers` we
modify our copy of `test.txt` and show below how to merge this with
the different version that exists up on the server.

## Verify the updates

As the original `ftravers` user, verify the updates the `testuser`
made.

    $ cd ~/projects/testrepo1/

Make some mods to `test.txt` file. This means what’s on the server
will conflict with what you have locally. So try to pull down the
changes that are on the server.

    $ git pull origin master

Do any merging required if auto-merge fails and push up your
changes.

    $ cd ~/projects/testrepo1/; git push

## Verify the changes as testuser

Now you can log back in as test user and pull down the changes.

    [testuser@local]$ cd ~/projects/testrepo1; git pull; cat test.txt

# Misc Tasks

## Branching

Create a new branch and begin working on it.

    git checkout -b <new branch name>

As you go developing the master branch may have moved along, so it is
useful to pull in the changes that have occured on master while you have
been editing on your branch.  While on your branch do:

     git rebase master

That will pull the changes that have occured on master while you've
been editing on your branch, into your branch.

## Pushing a branch to remote repository

    git push origin newfeature

Where `origin` is your remote name and `newfeature` is the name of
the branch you want to push up.

## Pull a remote branch

Check the remote branches

    git remote show origin

update your local repo so it is aware of new branches on ‘origin’.
    
    git fetch

create a local tracking branch:

    git checkout -b local-branch-name origin/remote-branch-name

where the first experimental is the name of your local branch that
maps to the branch name on the remote (origin) named (experimental) as
well.

## Delete a remote tracking branch

    git branch -d -r origin/<remote branch name>

origin/master is a remote tracking branch for
the master branch in the origin repo

### Deleting remote branch

Deleting is also a pretty simple task (despite it feeling a bit
kludgy):

    git push origin :newfeature

That will delete the newfeature branch on the origin remote, but
you’ll still need to delete the branch locally with git branch -d
newfeature.

## Compare Branches

Often you’ll be working on a branch, then switch back to the
master...and would like to know what is the difference between the two
branches.  The following shows files and how changed.

    git diff --name-status master..npe

# Branching, Merging best practices

Normally when you've created a branch you want to regularly do:

    git rebase master

This gets all the changes that have occurred on master while you are
on your branch and puts them *under* your commits.

When you are ready to merge back to master, you want to squash all
your commits into a single commit.

First find out which commits have occurred since you were on master
with either of the following:

    git log master..HEAD
    git log master..HEAD --oneline

Here is an example:

    $ git log master..HEAD --oneline
    0da7acd .
    574f56c .
    $

So I can see there have been two commits, and I want to squish these
into one.  These are listed most recent at top.

Next run an interactive rebase with:

    git rebase -i HEAD~2

Since I only have two commits, I use HEAD~2, if you have more commits,
change the number after HEAD~.  Now your editor will pop up allowing
you to start your rebase.  Now we will squish the newer commits into
the oldest commit.  During rebase the commits are listed in reverse
order to git log, with newest at the bottom.  My editor has the
following two lines at the top:

    pick 574f56c . <--- older commit
    pick 0da7acd . <--- newer commit

I change this to:

    pick 574f56c .
    squash 0da7acd .

This will merge the two commits into a single new commit.  Then just
save and exit out of your editor to go to the next step.  Another
editor window will popup where you can adjust the commit message for
this new single commit.

Now we are in a good position to create a proper patch file which we
can give to the code base owner, so they can easily see what you've
changed in the code.

# How to create and apply a patch with Git

## Create a patch file

You are on branch that you want to compare against master.

<pre><div class="sample_code">git format-patch <span class="parameter">master</span> --stdout &gt; <span class="parameter">file.patch</span></div></pre>

Take a look at what changes are in the patch

    git apply --stat file.patch

## Compare working directory against latest commit (HEAD)

    git diff HEAD --

## Compare Two Files

Then you might wonder what is the difference between a file that
exists in two different  
branches.

    git diff <branchA> <branchB> -- <file>
    git diff <commit> <commit> -- <file>

compare file: pom.xml with current and two commits ago:

    git diff HEAD HEAD^^ -- pom.xml
    git diff HEAD HEAD~2 -- pom.xml

tags: diff two files

## Bring down remote changes

Say the branch we are interested in bring remote changes down into is
‘master’. The first thing we do is ensure locally we are on the master
branch. If you are not on the master branch commit or stash your local
changes on the branch you are on and switch to the master branch.

    git checkout master

Now pull down the remote changes into your remote-tracking branch.
You can see your local branches and your remote-tracking branches by
doing: `git branch` and `git branch -r` respectively. When I do a `git
branch -r` I see that I have a branch called `origin/master`.

    $ git branch -r
      origin/master

So to safetly update my remote-tracking branch origin/master I simply
do:

    git fetch origin

Now I can compare the differences between my version of master and the
remote version. I simply do:

    $ git diff --name-status master origin/master

To see a list of files that have been changed. Then I can get the  
full diff file by dropping the `--name-status` parameter:

    $ git diff master origin/master > ~/tmp/diff.diff

I output the results of that command to a file that I can later
open  
in emacs to get a better view of what the changes actually are.

If you are happy with the differences then you can merge them:

    $ git merge origin/master

## (segue) Resolving merge problems for a single file

Say we have a file that can’t be automatically merged. The
branches  
are ‘bugFix’ and ‘master’, and the file it is complaining about
is:  
‘src/main/java/com/acme/My.java’. First commit all changes on
branch  
‘bugFix’, then switch to ‘master’ and try to merge. My.java fails  
auto merge. Get the diff for this file with:

    git diff bugFix master src/main/java/com/acme/My.java > ~/tmp/My.java.diff

Now get the My.java on the bugFix branch and apply this patch to it
in  
emacs.

    mv src/main/java/com/acme/My.java src/main/java/com/acme/My.java.master
    git checkout bugFix src/main/java/com/acme/My.java

Now open both files in emacs and run command:
`A-x ediff-patch-buffer`  
and pick the correct buffers for the patch and the file to patch.

Finally you can use ‘n’, ‘p’ for next and previous patch chunks.
You  
can type ‘?’ in the mini-buffer to get a list of commands to help
you.

## (segue – over)

The following workflow has us list all of our branch (-a includes
the remote branches)

    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ git branch -a
      activity
    * master
      remotes/origin/master
    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ git fetch origin

Check which files have changed, and what has changed in the files

    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ git diff --name-status master..remotes/origin/master
    M       src/main/java/com/oracle/ngsp/crmod/ServiceRequest.java
    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ git diff master..remotes/origin/master src/main/java/com/oracle/ngsp/crmod/ServiceRequest.java
    ...a lot of diff info...

Finally we can merge the branch into our master branch

    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ git branch -a
      activity
    * master
      remotes/origin/master
    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ git merge remotes/origin/master
    Updating 2872496..3f88c4a
    Fast-forward
     .../java/com/oracle/ngsp/crmod/ServiceRequest.java |   47 ++++++++++----------
     1 files changed, 24 insertions(+), 23 deletions(-)
    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ 

Finally, we might just want to make sure if anything got added that
we push that back up  
to the remote too.

    ftravers@ftravers-laptop:~/projects2/crmod-ws-wrapper$ git push
    Everything up-to-date

## Manual Merge

Sometimes the auto-merge will report an inability to auto-merge for
you:

    CONFLICT (content): Merge conflict in src/main/java/com/oracle/ngsp/crmod/Activity.java
    Automatic merge failed; fix conflicts and then commit the result.

Now type:

    git mergetool


## Unstaging a file

To unstage the file: `src/site/apt/build.apt~`

    git reset HEAD src/site/apt/build.apt~

## Git Ignore file

Create a file called `.gitignore` in the project root and put lines
like the following in it.

    # a comment - this is ignored
    *.a       # no .a files
    !lib.a    # but do track lib.a, even though you're ignoring .a files above
    /TODO     # only ignore the root TODO file, not subdir/TODO
    build/    # ignore all files in the build/ directory
    doc/*.txt # ignore doc/notes.txt, but not doc/server/arch.txt
    target/
    *.diff
    *~


## Committing

Before you commit, you’ll want to checkout what’s going on. The
command  
to see what has been modified, added, etc.. is:

    git status

To get a feel for which files have been changed and by how much
try:

    git diff --stat

which gives you a sense of which files have been changed and by how
much. To  
see what has changed in a given file do:

    git diff <filename>    # Command Format
    git diff src/test/java/com/oracle/ngsp/crmod/ServiceRequestTest.java     # Command Example

Now you can add the file into the staging area with:

    git add src/test/java/com/oracle/ngsp/crmod/ServiceRequestTest.java

Then you can commit it with:

    git commit -m"<commit_Message>"   # Command Format
    git commit -m"Removed testGetActivities from ServiceRequestTest"     # Command Example

## See changes to a file

    git log -p <path to file>

# Using Git on Windows

* Install `mysysgit`

In the selection "how would you like to user Git from the command
line?", the default is "use Git bash only", which is ok

* Generate your public/private key pair.  Open GIT-Bash and type:

    ssh-keygen

Just hit enter for all the prompts, don't use a passphrase.

The public key is the file:

    ~/.ssh/id_rsa.pub

Email me your public key.

# Change your routing

If you are plugged on a company network where SSH is not tolerated
but on the other hand have access to a wifi network where it is,   
there is a way to have GIT working without plugging/unplugging your
network cable

-   connect to the wifi network and make sure you can access
    internet

You can now figure out two informations from the traceroute
command:

    bvanders-laptop:~ bvanders$ traceroute spicevan.com
    traceroute to spicevan.com (173.236.138.100), 64 hops max, 40 byte packets
     1  xxx.xxxx.xxx (192.168.0.1)  163.935 ms  167.994 ms  153.271 ms

*Note: on windows, the command would be tracert spicevan.com but the result would be similar*

*192.168.0.1* is your gateway  
*173.236.138.100* is spicevan.com’s ip address

-   connect your ethernet cable and type the following command to
    add a static route:

`sudo route add 173.236.138.100/32 192.168.0.1`

*Note: on windows, the command is `route ADD 173.236.138.100 MASK 255.255.255.0 192.168.0.1`*

You should now be able to test it with the command `git status`

# Tags

List the tags with 

    git tag -l 

and then checkout a specific tag: 

    git checkout <tag_name>

# Recipes

## Cherry pick files from other branch

What is the best way to merge selective files from one development
branch to another while leaving behind everything else?

    #You are in the branch you want to merge to
    git checkout <branch_you_want_to_merge_from> <file_paths...>

## Restore deleted file

Q: I deleted a file, committed that delete. How do I find the
commit where that file was deleted and how do I restore just that
file?

A: Find the last commit that affected the given path. As the file
isn’t in the HEAD commit, this commit must have deleted it.

    git rev-list -n 1 HEAD -- <file_path>

Then checkout the version at the commit before.

    git checkout <deleting_commit>^ -- <file_path>

## I committed something in the past for one file and I want to undo that commit.

open gitk in the project and navigate the history to find the
commit you want to undo. Make sure you have ‘patch’ selected in
bottom right window. You can right click on the filename and choose
‘Highlight this only’. Look in the box: ‘SHA1 ID:’ to get a sense
of the SHA1 ID for this commit. Then do a: `git log` in the
terminal so you can select (copy/paste) this SHA1. Make sure you
have the version number (SHA1) of the commit before the commit that
has the change. Once you have the SHA1 you want to checkout this
version like so:

git checkout a5ab6dd2505a5bcbdeafcb393cafd6a404ef051d —
src/main/java/com/oracle/git/sesReader/SesReader.java

## revert (reset) a single file

This one is hard to find out there so here it is. If you have an
uncommitted change (its only in your working copy) that you wish to
revert (in SVN terms) to the copy in your latest commit, do the
following:

    git checkout filename

## Move remote repo

Say I want to start using a new remote repository. Say also that this
remote repository doesn’t have the code there yet.

-   Change Origin

The first thing to do is change where origin points to

    $ git remote -v
    origin  ft_git3@spicevan.com:elisp.git (fetch)
    origin  ft_git3@spicevan.com:elisp.git (push)
    $ git remote set-url origin git@linux1.hk.oracle.com:elisp.git
    $ git push origin master:refs/heads/master

If the repo already exists on the server (say for your colleagues  
after you’ve moved it there), they just have to do the @git
remote  
set-url...@ step, followed by:

    git pull origin master

## Setting up a public repository

### Install Process

-   ensure [rpmforge](/applications.html#rpmforge) is
    installed on your server

-   install xinetd

    yum -y install xinetd

-   install the git-daemon

    yum -y install git-daemon

-   open the correct port

    system-config-securitylevel-tui --quiet --port 9418

-   enable git for xinetd

    [root@linux1 elisp.git]# cat /etc/xinetd.d/git
    service git
    {
            disable         = no
            socket_type     = stream
            wait            = no
            user            = nobody
            server          = /usr/libexec/git-core/git-daemon
            server_args     = --base-path=/home/git/repositories --syslog --inetd --verbose
            log_on_failure  += USERID
    }

### For each particular repo you want public

-   ON THE GIT SERVER in the git repos you want to be publicly
    readable

do (the following example, elisp is the repos I want readable)
    chmod 755 elisp.git/
    cd /home/git/repositories/elisp.git/
    touch git-daemon-export-ok

-   Now from anywhere else (some client machine) do:

    git clone git://linux1.hk.oracle.com/elisp.git

## Normal Development Workflow

The following example demonstrates how a normal coding workflow should
be executed.  A simple file will be used to demonstrate how these
things work.  The file is called `testBranch.mmd` and only has the
following line in it to start with.  It is on the master branch.

    Test file, line 1.    

## Branch

The first step is to make a branch, we'll call it `branch1`.

    git checkout -b branch1

Now lets add an additional line, and commit our change on `branch1`.

    git commit -am'First commit on branch1'

The new file looks like:

    Test file, line 1.
    Second line. First commit on branch1.    

Lets add another line

    Test file, line 1.
    Second line. First commit on branch1.
    2nd commit on branch1.

and do another commit:

    git commit -am'2nd commit on branch1'

Now lets switch back to master:




# Bazaar

Bazaar is another VCS similar to GIT but apparently easier to use.

## Getting started

    bzr init
    bzr add
    bzr commit -m "Initial import"
    bzr log



