# Keyboard Shortcuts

## Chrome

Key	      | Action
--------- | ------------------------



## Google Search

Key	      | Action
--------- | ------------------------
J	      | Selects the next result.
K	      | Selects the previous result.
O	      | Opens the selected result.
[Enter]	  | Opens the selected result.
/	      | Puts the cursor in the search box.
[Esc]	  | Removes the cursor from the search box.
