## Rectangle

To make a non-filled rectangle.  Draw the rectangle and then open the
stroke-fill dialogue: `Ctrl-Shift-F` (or in the Object menu).  In the
fill tab select the first icon which means `no-paint`.

## Draw a straight line

`Shift-F6` to get right tool.  Click on start and finish, then
hit enter.

## Adjust canvas size to fit image

File > Document Properties > Resize drawing to 

* note: if you have hidden objects, complicating the canvas resize,
  choose: `View > Display Mode > Outline`

## Alignment

`Ctrl-Shift-A`.

## Group & Ungroup

`Ctrl-g` & `Ctrl-u`
