#!/bin/bash 
# Jenkins init file for starting and stopping.
# chkconfig: 35 80 30
# description: Jenkins startup script
 
# Source function library.
. /etc/rc.d/init.d/functions
 
JENKINS_OWNER="fenton"	
JENKINS_HOME="/home/fenton/bin"

case "$1" in	
	start)	
		echo -n $"Starting Jenkins:"	
		su - $JENKINS_OWNER -c "java -Dhttp.proxyHost=www-proxy.sg.oracle.com -Duser.timezone=GMT+8 -jar $JENKINS_HOME/jenkins.war"	
		echo "OK"	 
		;;	

	stop)
		echo "Stop doesn't do anything...sorry!"	
		;;

	*)	
		echo $"Usage: $0 start"	 
		;;
esac
