# Basic Commands

## Start server

    sudo systemctl start mysqld

conf file:

    /etc/mysql/my.conf

## Set root password

### first time

`mysqladmin -u root password supersecretpasswd`

### reset root password

`$ mysqladmin -u root -p'supersecretpasswd' password newsupersecretpasswd`

## Login

`mysql -u root -p` or if no password is defined for the root user,
just: `mysql -u root` will work.

## Show databases and tables

Show all databases, use a database, see which tables are defined in
that DB, then quit.

    mysql> show databases;
    mysql> use test;
    mysql> show tables;

### Dump Database

    mysqldump -h localhost DATABASE > DATABASE.sql

### Create Table

    mysql> CREATE TABLE example ( id INT, data VARCHAR(100));

### Drop Table

    mysql> DROP TABLE example;

### See the columns in a table

    describe DocMeta;

### Add column to table

    ALTER TABLE contacts ADD email VARCHAR(60);

# Installation

If you don't have root permissions you can launch a local version of mysql.  Download and untar
the *.tar version of Community Edition MySQL.

# Common Use Cases

## Create new db and give user rights to it

-   In the following example we log in as root.

    $ mysql -u root -p

-   Create a db called: `amarokdb`.

    mysql> create database amarokdb;

-   We allow user amarokuser to connect to the server from
    localhost using the password amarokpasswd:

-   Side note you may want to give an existing user access versus
    creating the user. To see a list of users do:

    mysql> select host, user from mysql.user;

Otherwise create a new user.

    mysql> grant usage on *.* to amarokuser@localhost identified by 'amarokpasswd';

-   And finally we grant all privileges on the amarok database (\*
    means all tables) to this user:

    mysql> grant all privileges on amarokdb.* to amarokuser@localhost ;

-   And that’s it. You can now check that you can connect to the
    MySQL server using this command:

    $ mysql -u amarokuser -p'amarokpasswd' amarokdb

-   Drop a user:

    drop user 'amarokuser'@'localhost';

## Who has access to what

The following command will show which users have access to which
databases:

    mysql> select user, host, db from mysql.db;

# Maven

    <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>5.1.9</version>
    </dependency>



