[home](/index.html) \> OVM Manager & Template Builder

Table of Contents

1.  [Overview](OVM_Manager_TemplateBuilder.html#Overview)

# Overview

I’m starting with an image built with the OVM Template Builder
Template available on eDelivery. I will rebuild my own image from
scratch as I don’t like using Templates that I didn’t build since I
don’t know what is happening inside them. For example there only
seems to be images based on OEL 5U3, when OEL 5U5 is available. So
this is a very vanilla situation.

As with all bare-bones OEL JeOS images please take
[these prepatory steps](oel.html) to get the system to a basic
level of usability.



