# Package Management - Python Eggs

## Debian Setup

```bash
$ sudo apt-get install python-setuptools
$ sudo easy_install -U PasteScript
```

## Create Shell Project

```bash
$ paster create --list-templates
$ paster create -t basic_package
```

After responding to some questions, such as project name, we get a
folder created by the name we used for our project.  In this tutorial
my project name is: **it_library**.

## Release Egg

You can create and upload the egg with:

```bash
$ cd it_library/
$ python setup.py bdist_egg register upload
Submitting dist/it_library-0.0.1dev-py2.7.egg to http://pypi.python.org/pypi
Server response (200): OK
```

## New Egg Version

Update version info in `setup.py` and re-release.

## Share with others

Have people go to [pypi.python.org](http://pypi.python.org/), and put
your project name into the search box at top right.

```bash
$ sudo easy_install -U it_library
```

## Local testing

If you want to install and test any changes you made, do:

```bash
$ sudo python setup.py install
```


**NOTE**: My test project is called: **it_library**, replace this with the name
of your project.


## References

* [Reference](http://wiki.python.org/moin/CheeseShopTutorial)
* [Python Eggs - Package Management](http://mrtopf.de/blog/en/a-small-introduction-to-python-eggs/)

# Language Reference

## Starting a Script

```python
##!/usr/bin/python
import sys
import os
def printHello(name):
    print "Hello: " + name
def goodbye(name)
```

Code blocks are **indented**.  To finish a code block un-indent.

## Command line arguments

```python
import sys
for arg in sys.argv:
    print arg
```

sys.argv is just a list

## Convert String -> Int -> String

```python
age = "12"
birthday = int(age) + 1
print "After your birthday you'll be: " + str(birthday)
```

## Files

### Reading

    f = open("../resources/htmlInputTestStrings.properties", 'r')
    for line in f:
        parts = string.split(line, '=')
        print parts

### Writing

    f = open("../resources/htmlInputTestStrings.properties", 'w')
    f.write("test")
    f.close()

## Switch / Case statements

    options = {0 : zero,
                1 : sqr,
                4 : sqr,
                9 : sqr,
                2 : even,
                3 : prime,
                5 : prime,
                7 : prime,
                }
    def zero():
        print "You typed zero.\n"
    def sqr():
        print "n is a perfect square\n"
    def even():
        print "n is an even number\n"
    def prime():
        print "n is a prime number\n"

Now that you have the switch case setup, you can actually use it by
simply doing a dictionary lookup:

    options[num]()

Thanks to the fact that Python functions are first class values, you
can use the functions as the values of the dictionary and then call
them via dictionary lookup.


## Data Types

### Lists

Empty list initialization
    
    myList = []

* The in operator can be used to check if an item is present in the list:

    if value in L:
        print "list contains", value

#### List functions

* size

Use `len(list)` to get length of a list.

* list.pop([i])

Remove the item at the given position in the list, and return it. If
no index is specified, a.pop() removes and returns the last item in
the list. (The square brackets around the i in the method signature
denote that the parameter is optional, not that you should type square
brackets at that position. You will see this notation frequently in
the Python Library Reference.)

### Dictionary

    tel = {'jack': 4098, 'sape': 4139}

#### Looping over Dictionaries

     hosts = { 'dev':'123', 'stg':'456' }
     for k, v in hosts.iteritems():

## Calling External Programs

* [Reference](http://www.doughellmann.com/PyMOTW/subprocess/)

### Get external program output

```python
import subprocess

output = subprocess.check_output(['ls', '-1'])
print 'Have %d bytes in output' % len(output)
print output
```

## Regex: Searching Strings

Code to extract string: version number: "0.3.0"

```python
import re
data = "<version>0.3.0-SNAPSHOT</version>"
matcher = re.compile("<version>(.*)-SNAPSHOT</version>", re.MULTILINE)
matched = matcher.search(data)
if matched != None:
  matched = matched.group(1)
```

`matched` should now contain the string: "0.3.0"

## global variables

```python
globvar = 0

def set_globvar_to_one():
    global globvar    # Needed to modify global copy of globvar
    globvar = 1

def print_globvar():
    print globvar     # No need for global declaration to read value of globvar

set_globvar_to_one()
print_globvar()       # Prints 1
```
