# Package Management - Python Eggs

## Debian Setup

```bash
sudo apt-get install python-setuptools
sudo easy_install -U PasteScript
paster create --list-templates
```

# Starting a Script

```python
#!/usr/bin/python
import sys
import os
def printHello(name):
    print "Hello: " + name
def goodbye(name)
```

Code blocks are **indented**.  To finish a code block un-indent.

# Command line arguments

```python
import sys
for arg in sys.argv:
    print arg
```

sys.argv is just a list

# Convert String -> Int -> String

```python
age = "12"
birthday = int(age) + 1
print "After your birthday you'll be: " + str(birthday)
```

# Files

## Reading

    f = open("../resources/htmlInputTestStrings.properties", 'r')
    for line in f:
        parts = string.split(line, '=')
        print parts

## Writing

    f = open("../resources/htmlInputTestStrings.properties", 'w')
    f.write("test")
    f.close()

# Switch / Case statements

    options = {0 : zero,
                1 : sqr,
                4 : sqr,
                9 : sqr,
                2 : even,
                3 : prime,
                5 : prime,
                7 : prime,
                }
    def zero():
        print "You typed zero.\n"
    def sqr():
        print "n is a perfect square\n"
    def even():
        print "n is an even number\n"
    def prime():
        print "n is a prime number\n"

Now that you have the switch case setup, you can actually use it by
simply doing a dictionary lookup:

    options[num]()

Thanks to the fact that Python functions are first class values, you
can use the functions as the values of the dictionary and then call
them via dictionary lookup.


# Data Types

## Lists

Empty list initialization
    
    myList = []

* The in operator can be used to check if an item is present in the list:

    if value in L:
        print "list contains", value

### List functions

* size

Use `len(list)` to get length of a list.

* list.pop([i])

Remove the item at the given position in the list, and return it. If
no index is specified, a.pop() removes and returns the last item in
the list. (The square brackets around the i in the method signature
denote that the parameter is optional, not that you should type square
brackets at that position. You will see this notation frequently in
the Python Library Reference.)

## Dictionary

    tel = {'jack': 4098, 'sape': 4139}

### Looping over Dictionaries

     hosts = { 'dev':'123', 'stg':'456' }
     for k, v in hosts.iteritems():

