# Python

## Command line arguments

    import sys
    for arg in sys.argv:
        print arg

sys.argv is just a list

## Data Types

### Dictionary

    tel = {'jack': 4098, 'sape': 4139}

#### Looping over Dictionaries

     hosts = { 'dev':'123', 'stg':'456' }
     for k, v in hosts.iteritems():

