# Basic Rails

[ref][tut1]

## Install rails

    gem install rails

## Install a javascript runtime

    gem install therubyracer

In your `Gemfile` put:

    gem 'therubyracer', require: "v8"

and run

    bundle install

## Create new rails app

Create an application called `catdb`

    rails new catdb

## Create DB

    rake db:create
    
## Start it up!

    rails server
    
Test by navigating to:

    http://127.0.0.1:3000/


# Behaviour Driven Development Rails

[ref][testing]

at the end of file: `config/environments/test/rb`, put:

```ruby
config.gem "rspec", :lib => false, :version => ">=1.2.2"
config.gem "rspec-rails", :lib => false, :version => ">=1.2.2"
config.gem "webrat", :lib => false, :version => ">=0.4.3"
config.gem "cucumber", :lib => false, :version => ">=0.2.2"
```

at the end of file: `Gemfile`, put:

```ruby
gem 'cucumber', '>= 0.2.2'
gem 'webrat', '>= 0.4.3'
gem 'rspec-rails', '>= 1.2.2'
gem 'rspec', '>= 1.2.2'
```







[testing]: http://railscasts.com/episodes/155-beginning-with-cucumber?view=asciicast
[tut1]: http://guides.rubyonrails.org/getting_started.html
