## Reference:

[First Steps](http://www.artima.com/scalazine/articles/steps.html)
[Eclipse and Scala](http://www.vogella.de/articles/Scala/article.html)


## Maven

    mvn org.apache.maven.plugins:maven-archetype-plugin:1.0-alpha-7:create -DarchetypeGroupId=org.scala-tools.archetypes -DarchetypeArtifactId=scala-archetype-simple -DarchetypeVersion=1.1 -DremoteRepositories=http://scala-tools.org/repo-releases -DgroupId=your.proj.gid -DartifactId=your-proj-id

I updated the scala version in the properties section like so:

    <scala.version>2.9.0-1</scala.version>

## Running Scala

Create a class that looks like the following:

    package secondScala;
     
    object App extends Application {
      override def main(args : Array[String]) { println( "Hello World!" )}
    }

    mvn compile; cd target/classes; scala secondScala.App

## Calling scala code from java project



## Functions/Methods

    def: myFunc( argName: String ) {
       ...
    }

    def max(x: Int, y: Int): Int = if (x < y) y else x

max: (Int,Int)Int

Formula:

A Scala function definition looks like this:

    def [function-name] ([parameter-name]: [parameter-type]) : [return-type] = [function-body]
    
so

    def taste (food: Consumable) : Opinion = evaluate(food)

defines a function called `taste` that takes a `Consumable` as a
parameter named `food` and returns an `Opinion`. It calls `evaluate` and
returns the result, which must be an `Opinion`

The last value is returned - no explicit return is required, but since
the language is strongly typed there is protection against
accidentally returning meaningless values of the wrong type


## Unit (java: void)

scala.Unit, is Scala's analogue to void in Java. The main difference
between Scala's Unit and Java's void is that Scala lets you write down
a value of type Unit, namely (), whereas in Java there is no value of
type void.

## vals & vars

Scala differentiates between vals, variables that are assigned once
and never change, and vars, variables that may change over their
lifetime.

## Defining Variables/Values

[val|var] [variable name] : [type] = [value to assign]

    val name : java.lang.String = "Fenton Travers"

Type comes *AFTER* variable/value name.

## Static Methods

Static members (methods or ﬁelds) do not exist in Scala. Rather than
deﬁning static members, the Scala programmer declares these members in
singleton objects


    object HelloWorld {
      def main(args: Array[String]) {
        println("Hello, world!")
      }
    } 

## Classes

One important difference is that classes in Scala can have parameters. This
is illustrated in the following deﬁnition of complex numbers.

    class Complex(real: Double, imaginary: Double) {
      def re() = real
      def im() = imaginary
    }

These arguments must be passed when creating an instance of class
Complex, as follows: 

    new Complex(1.5, 2.3). 

The class contains two methods, called re and im, which give access to
these two parts.

# Lift Web Framework

## Ref

[Lift Framework](http://scalalift.com/)

## Intro

A simple example:

hidden-templates/fancy.html

    <html><body class="fancy">
        <lift:bind name="contents"/>
    </body><html>

fish/tropical.html

    <lift:surround with="hidden-templates/fancy" at="contents">
        Floating above tropical fish is like being in a colorful cartoonland.
    </lift:surround>

Results in:

    <html class="fancy"><body class="fancy">
        Floating above tropical fish is like being in a colorful cartoonland.
    </body></html>

You can also simply embed a template inside another one using the
*embed tag:

    <lift:embed what="hidden-templates/footer"/>

Second Pass Notes:

no extension is provided on the template name to allow flexibility for
localization suffixes, file types, etc.  hidden-templates is not
required in the path.  if only the filename (without extension) is
specified, the whole view path will be searched.
