# Reference

# Tutorials

[Screens Tutorial](http://www.rackaid.com/resources/linux-screen-tutorial-and-how-to/)

# Cheatsheet

Command                 | Meaning
---------------         | -------------------------------------------------
screen                  | Start `screen`
Ctrl-A                  | To send a command to `screen` and not the shell
c                       | create a new window
n                       | (n)ext window
p                       | (p)rev window
k                       | (k)ill a window
d                       | (d)etach from a window.  You can re-attach later.
screen -ls              | list running screens
screen -r <screen name> | (r)e-attach.  Use screen name from screen -ls command
H                       | create a running log of session
M                       | Monitor screen for activity

