CSS: style.css

[ref](http://kennardconsulting.blogspot.com/2011/03/grokking-seam-forge-part-2.html)

## Getting Started

At the command prompt type:

    forge

Start a new project

<div class="sample_code">new-project --named <span class="parameter">NAME</span> --topLevelPackage <span class="parameter">PACKAGE</span> --projectFolder <span class="parameter">DIRECTORY_PATH</span></div>

## Scaffolding

Add scaffolding

    scaffold setup

Set up default index files, a default template and home-page. This
creates the page that users will first see when accessing your
application.

    scaffold create-indexes --overwrite

## Persistence

Set up persistence (JPA), and press ENTER to confirm installation of
any required facet dependencies and/or packaging types, and remember
to press TAB if you are not sure what comes next.

    persistence setup --provider {your JPA implementation} --container {your container}

    persistence setup --provider HIBERNATE --container JBOSS_6

<side_note>
If you do not wish to use a Java EE container default data-source, you
can also specify additional connection parameters such as JNDI
data-source names, JDBC connection information, and data-source
types. Note, however, that this means you will probably need configure
your application server to provide this new data-source and/or
database connection.
</side_note>

    new-entity --named Person
    new-field string --named name
    new-field string --named phoneNumber
    ls
    scaffold from-entity


    scaffold from-entity com.palifen.domain.Person.java

Some of the above generates errors...this stuff is in Alpha at the moment...so be it.

