[home](../index.html) \> [training](index.html) \> SSH

Table of Contents

{toc}

# Getting a signed security certificate:

-  

-   http://my.oracle.com/site/git/2727/11529/11536/11537/index.htm

# Windows, Linux, OS/X

If you are using a linux or OS/X you probably don’t have to do much
to make things work here.   
If you are using windows, you’ll need to install cygwin. Please
goto: http://www.cygwin.com/  
Cygwin, gives you the power of Linux on a windows box. Just go
through the default install.

When you are installing, specifically add: `OpenSSH` to the items
to install. If you need git specifically search for and add it too.
Several options will come up…just add them all.

![image](/images/installGitCygwin.png)

# Setup automatic login to ssh server

## Generate your public/private key pair

If you already have a private key DON’T create a new one. The
following command will let you know if you already have one.

    [root@del ~]# ssh-keygen

## Copy to server

Copy your public key to the server.

Command Format:

    ssh-copy-id [username]@[host]

Example:

    ssh-copy-id ftravers@spicevan.com

Test this works by logging into the server, and ensure it DOESN’T
ask you for a password now.

    [root@del ~]# ssh ftravers@spicevan.com

    [oracle@linux1 u02]$ ssh-copy-id oracle@myhelpstage.sg.oracle.com
    /usr/bin/ssh-copy-id: ERROR: No identities found
    [oracle@linux1 u02]$ ssh-agent $SHELL
    [oracle@linux1 u02]$ ssh-add
    Identity added: /home/oracle/.ssh/id_rsa (/home/oracle/.ssh/id_rsa)
    [oracle@linux1 u02]$ ssh-copy-id oracle@myhelpstage.sg.oracle.com

# sshd config

## Slow logins

in file: `/etc/ssh/sshd_config` set the following:

    GSSAPIAuthentication no

# have sshd run on another port

Add line like:   
Port 10122  
to:  
/etc/ssh/sshd\_config

-   Debian

sudo /etc/init.d/ssh restart

-   Redhat

[root@proddb ssh]\# service sshd reload

To test:

    ssh -p <port-number> <user>@<ipAddress>

update firewall:  
To add a new port, run the following and  
[root@ucm3 \~]\# /usr/bin/system-config-securitylevel-tui  
Choose Customize, add a line like:   
8888:tcp  
to the other ports section, OK, OK.  
[root@ucm3 \~]\# service iptables restart

==\> Automatically log into servers:  
\> If you haven’t already generated your key pair with: ssh-keygen
-t rsa, do so.  
\> grab the file: id\_rsa.pub and get it into the server you want
to auto ssh into, put it in  
the root directory /root.  
\> ssh into the host then do:   
cd /root/.ssh; cat ../id\_rsa.pub \>\> authorized\_keys; chmod 600
authorized\_keys; rm -f ../id\_rsa.pub

# SSL

To display certificate request information.

    openssl req -in server.csr -noout -text

Display certificate info:

    openssl x509 -in cert.cer -noout -text

Display private key information.

    openssl rsa -in key.pem -noout -text



