```bash
$ mount -t vboxsf fenton /home/fenton/host
```
variable             | meaning
-------------------- | -----------------------
fenton               | is the name of the share 
/home/fenton/host    | is the folder where the share will be mounted



