* Start Offline


<pre><div class="sample_code">cd <span class="parameter">WLS_HOME</span>/user_projects/domains/base_domain/bin</div></pre>

    . setDomainEnv.sh
    java weblogic.WLST

## Asset Locations

### Domain Templates

<pre><div class="sample_code">cd <span class="parameter">WLS_HOME</span>/common/templates/domains</div></pre>

### Script Samples

<pre><div class="sample_code">cd <span class="parameter">WLS_HOME</span>/common/templates/scripts/wlst</div></pre>

## Create Domain

* Syntax

    createDomain(domainTemplate, domainDir, user, password)

* Example

    createDomain('/
