#+BLOG: my-blog
#+POSTID: 72
#+DATE: [2013-04-05 Fri 10:02]
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil TeX:nil
#+CATEGORY: Transparent Organizations Solutionism
#+TAGS:
#+DESCRIPTION:
#+TITLE: Transparent Organizations

I was reading an interesting post from George Monbiot, [[http://www.monbiot.com/2013/04/01/the-spark-of-hope/][Spark of Hope]],
where he discussed two 'big ideas'.  A guaranteed income for everyone,
and a land value tax.  I do think these are probably good ideas, but
they both require the participation of the taxed.  Both transfer money
from rich to poor, which the rich will fight tooth and nail.  I guess
my inclination is to pursue things that have the same effect, ensuring
everyone has access to the requirements for human dignity, food,
housing, clothing, etc..., yet rely less on the benevolence of the
rich to achieve them.  How can the 'poor' organize themselves to
provide these things? 

The two principle structures for income creation and distribution have
been the private and public sectors.  These two sectors are only
somewhat successful in achieving the goals of human dignity for all.
Corporatism leads to a winner takes all, and bugger the rest.
Govermentism, tends towards a fascism, where corporations control
government, and use it to enforce with the army, police, the corporate
agenda.  Again winner takes all.  So what to do?

Personally, I think the solution is two-fold.  First we need to agree
on what we are doing.  Then second, how that will be done.  The 'what'
is as stated above, a minimum level of human dignity for all.  I think
that is a pretty easy 'what' to agree on.  The how is more what I'll
address in this article.

In my opinion, the principle problem with existing structures/sectors
is a lack of transparency.  If organizations had an extreme level of
transparency, then their motives could be examined, and a
determination made whether they progressed the common good or not.
But how to achieve the level of transparency necessary to build this
confidence?  Being a technologist, I'd apply the common techniques
used in the industry; open data, analytics, etc...  

This approach often gets characterized and criticised as being a
[[http://www.guardian.co.uk/global/2013/mar/20/save-everything-evgeny-morozov-review][Solutionist]], and I am a solutionist.  However, [[http://en.wikipedia.org/wiki/Evgeny_Morozov][Morozov's,]] critique
around solutionism comes about because of his mistrust of how
governments and corporations would use data acquired with solutionist
approaches.  These concerns ligitimately arrise because of their
opaque nature.  His attack isn't on the technology per se, but how it
might be used in some fascist, totalitarian way.

I don't believe that government/corporations can be changed to be
transparent enough.  They face conflicting forces, that push them to
be more opaque.  What I'm suggesting is that a third type of
organization would need to be created that has transparency as a
founding principle.  What to call it?  A Transpariment? Transparation?
More importantly, how to get from where we are to one of those?  

There are attempts from traditional structures to move in that
direction.  For example, see [[http://arstechnica.com/business/2013/03/urban-activists-hack-their-way-towards-open-government/2/][Oakland's]] city government initiatives.
However, we also see opposite moves, like the Harper government [[http://news.nationalpost.com/2013/04/01/information-commissioner-to-investigate-harper-governments-muzzling-of-federal-scientists/][trying
to muzzle scientists]].  Government because of it's power is too much
subject to the power of the corporatocy, so ultimately, I don't think
transperiment will spontaneously evolve from there.

There are other sectors of the economy not mentioned so far, namely
NGOs and cooperatives.  Yet these organization often run foul too, and
primarily it's around transparency.  For example, too much money [[https://www.google.com/webhp?sourceid%3Dchrome-instant&ion%3D1&ie%3DUTF-8#hl%3Den&sclient%3Dpsy-ab&q%3Dcharity%2520misspent%2520funds&oq%3D&gs_l%3D&pbx%3D1&fp%3Dd8dcd326a9cff53e&ion%3D1&bav%3Don.2,or.r_cp.r_qf.&bvm%3Dbv.44770516,d.aGc&biw%3D1596&bih%3D773][spent
on running the charity]], and not enough on behalf of those the charity
purports to serve.

So I guess that another type of organization would need to be made,
who's modus operandi is transparency.  That's the how.  The what,
IMHO, should be what all the other organization seek to do.  So I'd
like to see government, corporations, NGOs supplanted by these
Transpariments/Transparations.  Those names are awful, lets just pick
the acronym TO's (Transparent Organizations) for now.  These TO's
would likely be driven by disenchanted silicon valley'ites, for whom
the the Ayn Rand [[http://en.wikipedia.org/wiki/Objectivism_(Ayn_Rand)][Objectivism]] they found ultimately unfulfilling.
Those seeking to apply their knowledge to the true advantage of
humanity.  It is these people I seek and with whom I recon, a truly
bright spark of hope exists!


