We would like Susan to be able to test her spreadsheet before she
submits it to confirm that it is properly formatted.  To achieve this
we'll make a change to the `categorizationSpreadsheet` project so that
it can be run from the command line.

First thing we do is get the project onto it's own branch.
[Ref](http://docs/git.html#branching).

    $ cd projects/categorizationSpreadsheet
    $ git checkout -b runFromCommandLine

Now we probably need to modify the pom.xml so we can make an
executable jar
file. [Ref](http://docs/maven.html#assemblealldependentjarsintoonepackage)

Made changes to project, view the diff file to have a look.
Unfortunately the changes are quite radical so might lose the essence
of the change.

Here are the highlights.  I moved a lot of testing code out of the
tests into the ParserValidator class, so they'd be available in the
assembled jar.  Remember tests are NOT included in packaged artifacts.

I changed the SpreadSheetParser class to not be primarily static.  We
may want to use different versions of the spreadsheet and not always
use the one packaged in the jar file.

Okay let now try to create the executable jar.
[Ref](http://docs/maven.html#assemblealldependentjarsintoonepackage)

     mvn assembly:assembly


